// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Ostap00034/course-work-backend-order-service/ent/order"
	"github.com/Ostap00034/course-work-backend-order-service/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescTitle is the schema descriptor for title field.
	orderDescTitle := orderFields[1].Descriptor()
	// order.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	order.TitleValidator = orderDescTitle.Validators[0].(func(string) error)
	// orderDescDescription is the schema descriptor for description field.
	orderDescDescription := orderFields[2].Descriptor()
	// order.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	order.DescriptionValidator = orderDescDescription.Validators[0].(func(string) error)
	// orderDescPrice is the schema descriptor for price field.
	orderDescPrice := orderFields[3].Descriptor()
	// order.DefaultPrice holds the default value on creation for the price field.
	order.DefaultPrice = orderDescPrice.Default.(float32)
	// orderDescAddress is the schema descriptor for address field.
	orderDescAddress := orderFields[4].Descriptor()
	// order.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	order.AddressValidator = orderDescAddress.Validators[0].(func(string) error)
	// orderDescLongitude is the schema descriptor for longitude field.
	orderDescLongitude := orderFields[5].Descriptor()
	// order.LongitudeValidator is a validator for the "longitude" field. It is called by the builders before save.
	order.LongitudeValidator = orderDescLongitude.Validators[0].(func(string) error)
	// orderDescLatitude is the schema descriptor for latitude field.
	orderDescLatitude := orderFields[6].Descriptor()
	// order.LatitudeValidator is a validator for the "latitude" field. It is called by the builders before save.
	order.LatitudeValidator = orderDescLatitude.Validators[0].(func(string) error)
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderFields[11].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescUpdatedAt is the schema descriptor for updated_at field.
	orderDescUpdatedAt := orderFields[12].Descriptor()
	// order.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	order.DefaultUpdatedAt = orderDescUpdatedAt.Default.(func() time.Time)
	// order.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	order.UpdateDefaultUpdatedAt = orderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderDescID is the schema descriptor for id field.
	orderDescID := orderFields[0].Descriptor()
	// order.DefaultID holds the default value on creation for the id field.
	order.DefaultID = orderDescID.Default.(func() uuid.UUID)
}
